scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['${APP_HOST}:${APP_PORT}']
        labels:
          service: 'my-service'
          group: 'production'
rule_files:
  - 'alert.rules'
